import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#454747",
        "on-error-container": "#ffdad6",
        error: "#ffb4ab",
        "primary-fixed": "#d7e2ff",
        "primary-container": "#0071e3",
        "surface-bright": "#393939",
        "tertiary-container": "#747375",
        "surface-container-lowest": "#0e0e0e",
        "on-surface": "#e2e2e2",
        tertiary: "#c8c6c8",
        "on-tertiary-fixed": "#1b1b1d",
        "tertiary-fixed-dim": "#c8c6c8",
        "primary-fixed-dim": "#abc7ff",
        "secondary-fixed": "#e2e2e2",
        "on-primary": "#002f66",
        "on-error": "#690005",
        "surface-variant": "#353535",
        "on-surface-variant": "#c1c6d6",
        "on-tertiary-container": "#fdfafc",
        "inverse-primary": "#005cbb",
        "on-secondary-container": "#b4b5b5",
        "surface-container-high": "#2a2a2a",
        "on-primary-container": "#fcfbff",
        "surface-container": "#1f1f1f",
        "inverse-surface": "#e2e2e2",
        "tertiary-fixed": "#e4e2e4",
        "on-primary-fixed-variant": "#00458f",
        "error-container": "#93000a",
        "surface-container-highest": "#353535",
        "on-tertiary-fixed-variant": "#474649",
        "outline-variant": "#414753",
        "surface-tint": "#abc7ff",
        "surface-container-low": "#1b1b1b",
        background: "#131313",
        primary: "#abc7ff",
        "surface-dim": "#131313",
        "secondary-fixed-dim": "#c6c6c7",
        "secondary-container": "#454747",
        "inverse-on-surface": "#303030",
        secondary: "#c6c6c7",
        "on-tertiary": "#303032",
        surface: "#131313",
        "on-primary-fixed": "#001b3f",
        "on-secondary": "#2f3131",
        "on-secondary-fixed": "#1a1c1c",
        outline: "#8b919f",
        "on-background": "#e2e2e2",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "section-gap": "160px",
        "margin-page": "64px",
        gutter: "24px",
      },
      fontFamily: {
        "label-caps": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-xl": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "display-xl": ["80px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["19px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;
